apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tweply
  namespace: tweply
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.ingress.host }}`)
      kind: Rule
      services:
        - name: tweply
          port: 80
  tls:
    secretName: {{ .Values.ingress.tlsSecretName }}
